@Library('roboshop-shared-library@main') _

env.REPONAME="user"
env.TFDIR="mutable-infra"
backendInfra()


//  pipeline {
//      agent any 
//      options {
//          ansiColor('xterm')
//      }
//      parameters {
//          choice(name: 'ENV', choices: ['dev', 'prod'], description: 'Select Your Envirovment')
//          choice(name: 'ACTION', choices: ['apply', 'destroy'], description: 'Select Your Action')
//      }
//      stages {
//          stage('Terraform Init') {
//              steps {
//                  script { git branch: 'main', url: 'https://github.com/jogichennaiah/cart.git' }
//                  sh "terrafile -f ${WORKSPACE}/mutable-infra/env-${ENV}/Terrafile"
//                  sh "cd ${WORKSPACE}/mutable-infra"
//                  sh "terraform init -backend-config=env-${ENV}/${ENV}-backend.tfvars"
//              }
//          }
//          stage('Terraform Plan') {
//              steps {
//                  sh "cd ${WORKSPACE}/mutable-infra"
//                  sh "terraform plan -var-file=env-${ENV}/${ENV}.tfvars"
//              }
//          }
//          stage('Terraform Action') {
//              steps {
//                  sh "cd ${WORKSPACE}/mutable-infra"
//                  sh "terraform ${ACTION} -auto-approve -var-file=env-${ENV}/${ENV}.tfvars"
//              }
//          }
//      }
// }